# Website information
site_name: SYNC lab wiki
site_url: https://sourcefoundry.org/cinder/ 
site_author: SYNC lab
site_description: "Lab wiki of the SYNC lab based at Erasmus University Rotterdam, the Netherlands"
repo_url: https://github.com/eur-synclab/sync-wiki

# Page navigation

nav:

  - Welcome:
      - Home: "index.md"
      - The SYNC lab: "welcome/intro-sync.md"
      - How to contribute: "welcome/contribute.md"
  - How we work:
    - Code of conduct: "how-we-work/code-of-conduct.md"
    - Labmeetings: "how-we-work/labmeetings.md"
    - Collaboration tools: "how-we-work/collab-tools.md"
  - Open Science:
    - Open acccess publishing:
      - Information: "open-science/open-access-info.md"
      - How to: "open-science/open-access-how.md"
    - Data sharing:
      - The GDPR: "open-science/gdpr.md"
      - Publication packages: "open-science/pub-packages.md"
      - How to share data?: "open-science/data-sharing-how.md"
      - NeuroVault: "open-science/neurovault.md"
      - Data sharing agreement: "open-science/dsa-template.md"
    - Reproducibility:
      - Open software: "open-science/open-software.md"
      - Open code: "open-science/open-code.md"
    - Transparency:
      - Preregistration: "open-science/preregistration.md"
      - Open project checklists: "open-science/transparency-guidelines.md"
      - Open Science Framework: "open-science/osf.md"
  - Data management:
    - Data security protocol: "data-management/data-security.md"
    - Research Drive:
      - About: "data-management/research-drive-info.md"
      - How to: "data-management/research-drive-how.md"
    - File organization: "data-management/folder-structure.md"
    - Version control:
      - Basic principles: "data-management/vc-principles.md"
      - Git(hub): "data-management/vc-github.md"
      - Version control for data: "data-management/vc-datalad.md"
    - Metadata:
      - FAIR data: "data-management/FAIR.md"
      - Types of metadata: "data-management/types-metadata.md"
      - DMP and DPIA: "data-management/dmp-dpia-info.md"
      - Codebooks: "data-management/codebooks.md"
  - Data analysis:
    - Types of data analysis: "data-analysis/types-analysis.md"
    - LISA cluster: "data-analysis/LISA-how.md"
  - Reaching out to society:
    - Scicom and citizen science: "reaching-out/intro-scicom.md"
    - Outreach practices: "reaching-out/outreach-practices.md"
  - Getting started at the EUR:
    - Intro to the EUR!: "getting-started-eur/welcome-eur.md"
    - Time registration: "getting-started-eur/time-registration.md"
    - Finances: "getting-started-eur/finances.md"
    - Email signature: "getting-started-eur/email-signature.md"

theme:
  name: null
  custom_dir: cinder
  colorscheme: github  
  highlightjs: true  
  hljs_languages: 
   - yaml 

use_directory_urls: false

markdown_extensions: 

- admonition